# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hannes/export/freepbx_sysadmin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hannes/export/freepbx_sysadmin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hannes/export/freepbx_sysadmin/CMakeFiles /home/hannes/export/freepbx_sysadmin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hannes/export/freepbx_sysadmin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named packet_capture

# Build rule for target.
packet_capture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 packet_capture
.PHONY : packet_capture

# fast build rule for target.
packet_capture/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/packet_capture.dir/build.make CMakeFiles/packet_capture.dir/build
.PHONY : packet_capture/fast

#=============================================================================
# Target rules for targets named powermgmt

# Build rule for target.
powermgmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 powermgmt
.PHONY : powermgmt

# fast build rule for target.
powermgmt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/powermgmt.dir/build.make CMakeFiles/powermgmt.dir/build
.PHONY : powermgmt/fast

#=============================================================================
# Target rules for targets named set_hostname

# Build rule for target.
set_hostname: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 set_hostname
.PHONY : set_hostname

# fast build rule for target.
set_hostname/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_hostname.dir/build.make CMakeFiles/set_hostname.dir/build
.PHONY : set_hostname/fast

#=============================================================================
# Target rules for targets named change_dns

# Build rule for target.
change_dns: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 change_dns
.PHONY : change_dns

# fast build rule for target.
change_dns/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/change_dns.dir/build.make CMakeFiles/change_dns.dir/build
.PHONY : change_dns/fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 network
.PHONY : network

# fast build rule for target.
network/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/build
.PHONY : network/fast

#=============================================================================
# Target rules for targets named set_timezone

# Build rule for target.
set_timezone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 set_timezone
.PHONY : set_timezone

# fast build rule for target.
set_timezone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_timezone.dir/build.make CMakeFiles/set_timezone.dir/build
.PHONY : set_timezone/fast

#=============================================================================
# Target rules for targets named get_netplan_config

# Build rule for target.
get_netplan_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 get_netplan_config
.PHONY : get_netplan_config

# fast build rule for target.
get_netplan_config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_netplan_config.dir/build.make CMakeFiles/get_netplan_config.dir/build
.PHONY : get_netplan_config/fast

#=============================================================================
# Target rules for targets named notifications

# Build rule for target.
notifications: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 notifications
.PHONY : notifications

# fast build rule for target.
notifications/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notifications.dir/build.make CMakeFiles/notifications.dir/build
.PHONY : notifications/fast

#=============================================================================
# Target rules for targets named email_settings

# Build rule for target.
email_settings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 email_settings
.PHONY : email_settings

# fast build rule for target.
email_settings/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/email_settings.dir/build.make CMakeFiles/email_settings.dir/build
.PHONY : email_settings/fast

#=============================================================================
# Target rules for targets named get_raid

# Build rule for target.
get_raid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 get_raid
.PHONY : get_raid

# fast build rule for target.
get_raid/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/build
.PHONY : get_raid/fast

change_dns.o: change_dns.cpp.o
.PHONY : change_dns.o

# target to build an object file
change_dns.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/change_dns.dir/build.make CMakeFiles/change_dns.dir/change_dns.cpp.o
.PHONY : change_dns.cpp.o

change_dns.i: change_dns.cpp.i
.PHONY : change_dns.i

# target to preprocess a source file
change_dns.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/change_dns.dir/build.make CMakeFiles/change_dns.dir/change_dns.cpp.i
.PHONY : change_dns.cpp.i

change_dns.s: change_dns.cpp.s
.PHONY : change_dns.s

# target to generate assembly for a file
change_dns.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/change_dns.dir/build.make CMakeFiles/change_dns.dir/change_dns.cpp.s
.PHONY : change_dns.cpp.s

email.o: email.cpp.o
.PHONY : email.o

# target to build an object file
email.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/email_settings.dir/build.make CMakeFiles/email_settings.dir/email.cpp.o
.PHONY : email.cpp.o

email.i: email.cpp.i
.PHONY : email.i

# target to preprocess a source file
email.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/email_settings.dir/build.make CMakeFiles/email_settings.dir/email.cpp.i
.PHONY : email.cpp.i

email.s: email.cpp.s
.PHONY : email.s

# target to generate assembly for a file
email.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/email_settings.dir/build.make CMakeFiles/email_settings.dir/email.cpp.s
.PHONY : email.cpp.s

functions.o: functions.cpp.o
.PHONY : functions.o

# target to build an object file
functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/packet_capture.dir/build.make CMakeFiles/packet_capture.dir/functions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/change_dns.dir/build.make CMakeFiles/change_dns.dir/functions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/functions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_netplan_config.dir/build.make CMakeFiles/get_netplan_config.dir/functions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notifications.dir/build.make CMakeFiles/notifications.dir/functions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/email_settings.dir/build.make CMakeFiles/email_settings.dir/functions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/functions.cpp.o
.PHONY : functions.cpp.o

functions.i: functions.cpp.i
.PHONY : functions.i

# target to preprocess a source file
functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/packet_capture.dir/build.make CMakeFiles/packet_capture.dir/functions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/change_dns.dir/build.make CMakeFiles/change_dns.dir/functions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/functions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_netplan_config.dir/build.make CMakeFiles/get_netplan_config.dir/functions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notifications.dir/build.make CMakeFiles/notifications.dir/functions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/email_settings.dir/build.make CMakeFiles/email_settings.dir/functions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/functions.cpp.i
.PHONY : functions.cpp.i

functions.s: functions.cpp.s
.PHONY : functions.s

# target to generate assembly for a file
functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/packet_capture.dir/build.make CMakeFiles/packet_capture.dir/functions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/change_dns.dir/build.make CMakeFiles/change_dns.dir/functions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/functions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_netplan_config.dir/build.make CMakeFiles/get_netplan_config.dir/functions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notifications.dir/build.make CMakeFiles/notifications.dir/functions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/email_settings.dir/build.make CMakeFiles/email_settings.dir/functions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/functions.cpp.s
.PHONY : functions.cpp.s

get_netplan_config.o: get_netplan_config.cpp.o
.PHONY : get_netplan_config.o

# target to build an object file
get_netplan_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_netplan_config.dir/build.make CMakeFiles/get_netplan_config.dir/get_netplan_config.cpp.o
.PHONY : get_netplan_config.cpp.o

get_netplan_config.i: get_netplan_config.cpp.i
.PHONY : get_netplan_config.i

# target to preprocess a source file
get_netplan_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_netplan_config.dir/build.make CMakeFiles/get_netplan_config.dir/get_netplan_config.cpp.i
.PHONY : get_netplan_config.cpp.i

get_netplan_config.s: get_netplan_config.cpp.s
.PHONY : get_netplan_config.s

# target to generate assembly for a file
get_netplan_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_netplan_config.dir/build.make CMakeFiles/get_netplan_config.dir/get_netplan_config.cpp.s
.PHONY : get_netplan_config.cpp.s

hostname.o: hostname.cpp.o
.PHONY : hostname.o

# target to build an object file
hostname.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_hostname.dir/build.make CMakeFiles/set_hostname.dir/hostname.cpp.o
.PHONY : hostname.cpp.o

hostname.i: hostname.cpp.i
.PHONY : hostname.i

# target to preprocess a source file
hostname.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_hostname.dir/build.make CMakeFiles/set_hostname.dir/hostname.cpp.i
.PHONY : hostname.cpp.i

hostname.s: hostname.cpp.s
.PHONY : hostname.s

# target to generate assembly for a file
hostname.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_hostname.dir/build.make CMakeFiles/set_hostname.dir/hostname.cpp.s
.PHONY : hostname.cpp.s

ifupdown.o: ifupdown.cpp.o
.PHONY : ifupdown.o

# target to build an object file
ifupdown.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/ifupdown.cpp.o
.PHONY : ifupdown.cpp.o

ifupdown.i: ifupdown.cpp.i
.PHONY : ifupdown.i

# target to preprocess a source file
ifupdown.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/ifupdown.cpp.i
.PHONY : ifupdown.cpp.i

ifupdown.s: ifupdown.cpp.s
.PHONY : ifupdown.s

# target to generate assembly for a file
ifupdown.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/ifupdown.cpp.s
.PHONY : ifupdown.cpp.s

mdadm.o: mdadm.cpp.o
.PHONY : mdadm.o

# target to build an object file
mdadm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/mdadm.cpp.o
.PHONY : mdadm.cpp.o

mdadm.i: mdadm.cpp.i
.PHONY : mdadm.i

# target to preprocess a source file
mdadm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/mdadm.cpp.i
.PHONY : mdadm.cpp.i

mdadm.s: mdadm.cpp.s
.PHONY : mdadm.s

# target to generate assembly for a file
mdadm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/mdadm.cpp.s
.PHONY : mdadm.cpp.s

netplan.o: netplan.cpp.o
.PHONY : netplan.o

# target to build an object file
netplan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/netplan.cpp.o
.PHONY : netplan.cpp.o

netplan.i: netplan.cpp.i
.PHONY : netplan.i

# target to preprocess a source file
netplan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/netplan.cpp.i
.PHONY : netplan.cpp.i

netplan.s: netplan.cpp.s
.PHONY : netplan.s

# target to generate assembly for a file
netplan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/netplan.cpp.s
.PHONY : netplan.cpp.s

network.o: network.cpp.o
.PHONY : network.o

# target to build an object file
network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/network.cpp.o
.PHONY : network.cpp.o

network.i: network.cpp.i
.PHONY : network.i

# target to preprocess a source file
network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/network.cpp.i
.PHONY : network.cpp.i

network.s: network.cpp.s
.PHONY : network.s

# target to generate assembly for a file
network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/network.cpp.s
.PHONY : network.cpp.s

networkManager.o: networkManager.cpp.o
.PHONY : networkManager.o

# target to build an object file
networkManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/networkManager.cpp.o
.PHONY : networkManager.cpp.o

networkManager.i: networkManager.cpp.i
.PHONY : networkManager.i

# target to preprocess a source file
networkManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/networkManager.cpp.i
.PHONY : networkManager.cpp.i

networkManager.s: networkManager.cpp.s
.PHONY : networkManager.s

# target to generate assembly for a file
networkManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/networkManager.cpp.s
.PHONY : networkManager.cpp.s

networkd.o: networkd.cpp.o
.PHONY : networkd.o

# target to build an object file
networkd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/networkd.cpp.o
.PHONY : networkd.cpp.o

networkd.i: networkd.cpp.i
.PHONY : networkd.i

# target to preprocess a source file
networkd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/networkd.cpp.i
.PHONY : networkd.cpp.i

networkd.s: networkd.cpp.s
.PHONY : networkd.s

# target to generate assembly for a file
networkd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/networkd.cpp.s
.PHONY : networkd.cpp.s

notifications.o: notifications.cpp.o
.PHONY : notifications.o

# target to build an object file
notifications.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notifications.dir/build.make CMakeFiles/notifications.dir/notifications.cpp.o
.PHONY : notifications.cpp.o

notifications.i: notifications.cpp.i
.PHONY : notifications.i

# target to preprocess a source file
notifications.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notifications.dir/build.make CMakeFiles/notifications.dir/notifications.cpp.i
.PHONY : notifications.cpp.i

notifications.s: notifications.cpp.s
.PHONY : notifications.s

# target to generate assembly for a file
notifications.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notifications.dir/build.make CMakeFiles/notifications.dir/notifications.cpp.s
.PHONY : notifications.cpp.s

packet_capture.o: packet_capture.cpp.o
.PHONY : packet_capture.o

# target to build an object file
packet_capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/packet_capture.dir/build.make CMakeFiles/packet_capture.dir/packet_capture.cpp.o
.PHONY : packet_capture.cpp.o

packet_capture.i: packet_capture.cpp.i
.PHONY : packet_capture.i

# target to preprocess a source file
packet_capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/packet_capture.dir/build.make CMakeFiles/packet_capture.dir/packet_capture.cpp.i
.PHONY : packet_capture.cpp.i

packet_capture.s: packet_capture.cpp.s
.PHONY : packet_capture.s

# target to generate assembly for a file
packet_capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/packet_capture.dir/build.make CMakeFiles/packet_capture.dir/packet_capture.cpp.s
.PHONY : packet_capture.cpp.s

power_management.o: power_management.cpp.o
.PHONY : power_management.o

# target to build an object file
power_management.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/powermgmt.dir/build.make CMakeFiles/powermgmt.dir/power_management.cpp.o
.PHONY : power_management.cpp.o

power_management.i: power_management.cpp.i
.PHONY : power_management.i

# target to preprocess a source file
power_management.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/powermgmt.dir/build.make CMakeFiles/powermgmt.dir/power_management.cpp.i
.PHONY : power_management.cpp.i

power_management.s: power_management.cpp.s
.PHONY : power_management.s

# target to generate assembly for a file
power_management.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/powermgmt.dir/build.make CMakeFiles/powermgmt.dir/power_management.cpp.s
.PHONY : power_management.cpp.s

raid.o: raid.cpp.o
.PHONY : raid.o

# target to build an object file
raid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/raid.cpp.o
.PHONY : raid.cpp.o

raid.i: raid.cpp.i
.PHONY : raid.i

# target to preprocess a source file
raid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/raid.cpp.i
.PHONY : raid.cpp.i

raid.s: raid.cpp.s
.PHONY : raid.s

# target to generate assembly for a file
raid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/get_raid.dir/build.make CMakeFiles/get_raid.dir/raid.cpp.s
.PHONY : raid.cpp.s

timezone.o: timezone.cpp.o
.PHONY : timezone.o

# target to build an object file
timezone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_timezone.dir/build.make CMakeFiles/set_timezone.dir/timezone.cpp.o
.PHONY : timezone.cpp.o

timezone.i: timezone.cpp.i
.PHONY : timezone.i

# target to preprocess a source file
timezone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_timezone.dir/build.make CMakeFiles/set_timezone.dir/timezone.cpp.i
.PHONY : timezone.cpp.i

timezone.s: timezone.cpp.s
.PHONY : timezone.s

# target to generate assembly for a file
timezone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_timezone.dir/build.make CMakeFiles/set_timezone.dir/timezone.cpp.s
.PHONY : timezone.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... change_dns"
	@echo "... email_settings"
	@echo "... get_netplan_config"
	@echo "... get_raid"
	@echo "... network"
	@echo "... notifications"
	@echo "... packet_capture"
	@echo "... powermgmt"
	@echo "... set_hostname"
	@echo "... set_timezone"
	@echo "... change_dns.o"
	@echo "... change_dns.i"
	@echo "... change_dns.s"
	@echo "... email.o"
	@echo "... email.i"
	@echo "... email.s"
	@echo "... functions.o"
	@echo "... functions.i"
	@echo "... functions.s"
	@echo "... get_netplan_config.o"
	@echo "... get_netplan_config.i"
	@echo "... get_netplan_config.s"
	@echo "... hostname.o"
	@echo "... hostname.i"
	@echo "... hostname.s"
	@echo "... ifupdown.o"
	@echo "... ifupdown.i"
	@echo "... ifupdown.s"
	@echo "... mdadm.o"
	@echo "... mdadm.i"
	@echo "... mdadm.s"
	@echo "... netplan.o"
	@echo "... netplan.i"
	@echo "... netplan.s"
	@echo "... network.o"
	@echo "... network.i"
	@echo "... network.s"
	@echo "... networkManager.o"
	@echo "... networkManager.i"
	@echo "... networkManager.s"
	@echo "... networkd.o"
	@echo "... networkd.i"
	@echo "... networkd.s"
	@echo "... notifications.o"
	@echo "... notifications.i"
	@echo "... notifications.s"
	@echo "... packet_capture.o"
	@echo "... packet_capture.i"
	@echo "... packet_capture.s"
	@echo "... power_management.o"
	@echo "... power_management.i"
	@echo "... power_management.s"
	@echo "... raid.o"
	@echo "... raid.i"
	@echo "... raid.s"
	@echo "... timezone.o"
	@echo "... timezone.i"
	@echo "... timezone.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

